spring:
  application:
    name: sling-search-challenge
  main:
    lazy-initialization: false

adapters:
  persistence:
    datasource:
      url: "${DB_URL}"
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      driverClassName: org.postgresql.Driver
      hikari:
        maximumPoolSize: 10
        minimumIdle: 2
        idleTimeout: 30000
        maxLifetime: 1800000
        connectionTimeout: 20000
    jpa:
      databasePlatform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

  kafka:
    topic: ms.sling.search.write.v1
    servers: "${KAFKA_SERVERS}"
    consumer:
      groupId: ms-sling-search-consumer
      session:
        timeout: 15000
      max:
        poll:
          records: 10
          interval:
            ms: 4000
    producer:
      key: ms-sling-search
      retries: 3
      acks: all
      max:
        flight:
          request: 5
      enable:
        idempotence: true
      batch:
        size: 16384
      buffer:
        memory: 33554432
      linger:
        ms: 10

