spring:
  application:
    name: sling-search-challenge

adapters:
  persistence:
    datasource:
      url: jdbc:postgresql://localhost:5432/sling_db
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      driverClassName: org.postgresql.Driver
      hikari:
        maximumPoolSize: 10
        minimumIdle: 2
        idleTimeout: 30000
        maxLifetime: 1800000
        connectionTimeout: 20000
    jpa:
      databasePlatform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update

  kafka:
    topic: ms.sling.search.write.v1
    servers: localhost:9092
    producer:
      key: ms-sling-search
      retries: 3
      acks: all
      max:
        flight:
          request: 5
      enable:
        idempotence: true
      batch:
        size: 16384
      buffer:
        memory: 33554432
      linger:
        ms: 10

